# Tomcat Setting
server:
  servlet:
    context-path: /sample
  #port: ${PORT}
  port: 8080
  tomcat:
    use-relative-redirects: true
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

# DB
spring:
  h2:
    console:
      enabled: true
  datasource:
    #In-memory DB
    #driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver
    # url: ${URL}
    # username: ${USERNAME}
    # password: ${PASSWORD}
    url: jdbc:h2:./h2db/sampledb
    username: username
    password: password
    initialization-mode: always
  session:
    store-type: none
  #  redis:
  #    host: ${REDIS_HOST}
  #    password: ${REDIS_PASSWORD}
  #    port: ${REDIS_PORT}
  thymeleaf:
    cache: false
    mode: HTML
  # JPA
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
# log
logging:
  level:
    org.springframework.web: info
    org.hibernate: info

# Spring Actuator Setting
# healthチェック
# curl -X GET http://localhost:8090/sample/actuator/health | jq
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # Shutdown
  # curl -X POST http://localhost:8090/sample/actuator/shutdown | jq
  endpoint:
    shutdown:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
security:
  ignore-spring-security-ant-pattern: /img/**, /css/**, /js/**, /webjars/**,/h2-console/**,/actuator/**
