version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo-java-spring
    steps:
      - checkout
      - run:
          name: run_build
          command: sh run_build.sh 1
  # EC2にSSH接続し、ビルドを実行
  build:
    machine:
      image: circleci/classic:edge
    steps:
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
            - "46:4c:fd:fd:5f:a4:25:e4:a1:0e:be:a6:18:d5:98:32"
      - run:
          name: DockerImage Build
          command: ssh ${USER_NAME}@${HOST_NAME} 'cd /work/docker-portfolio/spring-sample && git pull origin master && sh run_build.sh && cd /work/docker-portfolio/ && docker stop akazawa_spring && docker rm akazawa_spring && docker rmi -f docker-portfolio_springapp openjdk'
  # EC2にSSH接続し、デプロイ、アクチュエーターを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
            - "46:4c:fd:fd:5f:a4:25:e4:a1:0e:be:a6:18:d5:98:32"
      - run:
          name: DockerRun
          command: ssh ${USER_NAME}@${HOST_NAME} 'docker-compose up -d'
      - run:
          name: sleep 60s
          command: sleep 60
      - run:
          name: actuator
          command: curl -X GET https://kemper0530.com/sample/actuator/health
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
